import type { Metadata } from "next";
import { Archivo_Narrow, Archivo } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";

const archivoNarrow = Archivo_Narrow({
	weight: ["400", "500", "600", "700"],
	variable: "--font-primary",
	subsets: ["latin"],
});

const archivo = Archivo({
	weight: ["400", "500", "600", "700"],
	variable: "--font-secondary",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${archivoNarrow.variable} ${archivo.variable} antialiased`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
